import { useState } from 'react'
import { ArrowUp, Bot, CheckCircle2, Code2, Sparkles, User } from 'lucide-react'
import { apiService } from '../services/api'
import DataTable from '../components/DataTable'
import ChartCard from '../components/ChartCard'
import ErrorMessage from '../components/ErrorMessage'
import LoadingSpinner from '../components/LoadingSpinner'
const examples = ['What is the total revenue?', 'Show revenue by region', 'Which category has the highest profit?', 'What is the monthly revenue trend?', 'Show the top 10 products by revenue']
export default function AIQuery() { const [question, setQuestion] = useState(''); const [result, setResult] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const submit = async (e) => { e?.preventDefault(); if (!question.trim()) return; setLoading(true); setError(''); try { const response = await apiService.query(question.trim()); setResult(response.data) } catch (err) { setError(err.message) } finally { setLoading(false) } }; return <div className="page query-page"><div className="page-heading"><div><p className="eyebrow">AI QUERY</p><h1>Ask your data.</h1><p className="muted">Natural language in. Governed insight out.</p></div><span className="ai-badge"><span /> Agent ready</span></div><div className="query-hero"><div className="query-icon"><Sparkles size={24} /></div><h2>What would you like to understand?</h2><p>MetricMind will interpret your question, generate safe SQL, and return a visual answer.</p><form onSubmit={submit} className="query-input-wrap"><textarea value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="Ask MetricMind anything about your data..." rows="3" /><button className="query-submit" disabled={loading || !question.trim()} aria-label="Submit query">{loading ? <LoadingSpinner /> : <ArrowUp size={20} />}</button></form><div className="examples"><span>Try asking</span>{examples.map((example) => <button key={example} onClick={() => setQuestion(example)}>{example}</button>)}</div></div>{error && <ErrorMessage message={error} />}{result && <div className="results-area"><div className="conversation"><div className="message user"><div className="message-avatar"><User size={15} /></div><div><span className="message-label">You asked</span><p>{result.question}</p></div></div><div className="message assistant"><div className="message-avatar"><Bot size={15} /></div><div><span className="message-label">MetricMind</span><p>{result.answer}</p><div className="result-meta"><span><CheckCircle2 size={14} /> {result.row_count} rows</span><span>{result.execution_time_ms} ms</span></div></div></div></div><div className="result-grid"><section className="panel sql-panel"><div className="panel-heading"><div><h3><Code2 size={16} /> Generated SQL</h3><span>Validated read-only query</span></div></div><pre>{result.sql}</pre></section><ChartCard title="Suggested visualization" data={result.data} type={result.chart?.type === 'gauge' ? 'bar' : result.chart?.type} xKey={result.chart?.x} yKey={result.chart?.y} /><section className="panel result-table"><div className="panel-heading"><div><h3>Query results</h3><span>{result.row_count} records returned</span></div></div><DataTable data={result.data} /></section></div></div>}</div> }
